import type { WorldCup2026Fixture } from "./types";

export const WORLD_CUP_2026_FIXTURES = [
  {
    fixtureKey: "wc2026-match-001",
    matchNumber: 1,
    matchSlug: "world-cup-2026-mexico-vs-south-africa-2026-06-11",
    stage: "group_stage",
    groupKey: "group-a",
    roundLabel: "Group Stage",
    kickoffDateET: "2026-06-11",
    kickoffTimeET: "15:00",
    kickoffAt: "2026-06-11T19:00:00Z",
    timezone: "America/New_York",
    homeTeamKey: "mexico",
    awayTeamKey: "south-africa",
    homeTeamFifaCode: "MEX",
    awayTeamFifaCode: "RSA",
    venueKey: "mexico-city",
    hostCity: "Mexico City",
    hostCountry: "Mexico",
    apiFootballFixtureId: 1489369,
    apiFootballExternalId: "api-football:fixture:1489369",
    statusHint: "scheduled",
    sourceNotes:
      "Extracted from FIFA official match schedule PDF grid. API-Football id included only when already verified in UFO Predictor.",
  },
  {
    fixtureKey: "wc2026-match-002",
    matchNumber: 2,
    matchSlug: "world-cup-2026-south-korea-vs-czech-republic-2026-06-12",
    stage: "group_stage",
    groupKey: "group-a",
    roundLabel: "Group Stage",
    kickoffDateET: "2026-06-11",
    kickoffTimeET: "22:00",
    kickoffAt: "2026-06-12T02:00:00Z",
    timezone: "America/New_York",
    homeTeamKey: "south-korea",
    awayTeamKey: "czech-republic",
    homeTeamFifaCode: "KOR",
    awayTeamFifaCode: "CZE",
    venueKey: "guadalajara",
    hostCity: "Guadalajara",
    hostCountry: "Mexico",
    apiFootballFixtureId: 1538999,
    apiFootballExternalId: "api-football:fixture:1538999",
    statusHint: "scheduled",
    sourceNotes:
      "Extracted from FIFA official match schedule PDF grid. API-Football id included only when already verified in UFO Predictor.",
  },
  {
    fixtureKey: "wc2026-match-003",
    matchNumber: 3,
    matchSlug: "world-cup-2026-canada-vs-bosnia-herzegovina-2026-06-12",
    stage: "group_stage",
    groupKey: "group-b",
    roundLabel: "Group Stage",
    kickoffDateET: "2026-06-12",
    kickoffTimeET: "15:00",
    kickoffAt: "2026-06-12T19:00:00Z",
    timezone: "America/New_York",
    homeTeamKey: "canada",
    awayTeamKey: "bosnia-herzegovina",
    homeTeamFifaCode: "CAN",
    awayTeamFifaCode: "BIH",
    venueKey: "toronto",
    hostCity: "Toronto",
    hostCountry: "Canada",
    apiFootballFixtureId: 1539000,
    apiFootballExternalId: "api-football:fixture:1539000",
    statusHint: "scheduled",
    sourceNotes:
      "Extracted from FIFA official match schedule PDF grid. API-Football id included only when already verified in UFO Predictor.",
  },
  {
    fixtureKey: "wc2026-match-004",
    matchNumber: 4,
    matchSlug: "world-cup-2026-usa-vs-paraguay-2026-06-13",
    stage: "group_stage",
    groupKey: "group-d",
    roundLabel: "Group Stage",
    kickoffDateET: "2026-06-12",
    kickoffTimeET: "21:00",
    kickoffAt: "2026-06-13T01:00:00Z",
    timezone: "America/New_York",
    homeTeamKey: "usa",
    awayTeamKey: "paraguay",
    homeTeamFifaCode: "USA",
    awayTeamFifaCode: "PAR",
    venueKey: "los-angeles",
    hostCity: "Los Angeles",
    hostCountry: "USA",
    apiFootballFixtureId: 1489370,
    apiFootballExternalId: "api-football:fixture:1489370",
    statusHint: "scheduled",
    sourceNotes:
      "Extracted from FIFA official match schedule PDF grid. API-Football id included only when already verified in UFO Predictor.",
  },
  {
    fixtureKey: "wc2026-match-005",
    matchNumber: 5,
    matchSlug: "world-cup-2026-haiti-vs-scotland-2026-06-14",
    stage: "group_stage",
    groupKey: "group-c",
    roundLabel: "Group Stage",
    kickoffDateET: "2026-06-13",
    kickoffTimeET: "21:00",
    kickoffAt: "2026-06-14T01:00:00Z",
    timezone: "America/New_York",
    homeTeamKey: "haiti",
    awayTeamKey: "scotland",
    homeTeamFifaCode: "HAI",
    awayTeamFifaCode: "SCO",
    venueKey: "boston",
    hostCity: "Boston",
    hostCountry: "USA",
    apiFootballFixtureId: null,
    apiFootballExternalId: null,
    statusHint: "scheduled",
    sourceNotes:
      "Extracted from FIFA official match schedule PDF grid. API-Football id included only when already verified in UFO Predictor.",
  },
  {
    fixtureKey: "wc2026-match-006",
    matchNumber: 6,
    matchSlug: "world-cup-2026-australia-vs-turkiye-2026-06-13",
    stage: "group_stage",
    groupKey: "group-d",
    roundLabel: "Group Stage",
    kickoffDateET: "2026-06-13",
    kickoffTimeET: "00:00",
    kickoffAt: "2026-06-13T04:00:00Z",
    timezone: "America/New_York",
    homeTeamKey: "australia",
    awayTeamKey: "turkiye",
    homeTeamFifaCode: "AUS",
    awayTeamFifaCode: "TUR",
    venueKey: "vancouver",
    hostCity: "Vancouver",
    hostCountry: "Canada",
    apiFootballFixtureId: null,
    apiFootballExternalId: null,
    statusHint: "scheduled",
    sourceNotes:
      "Extracted from FIFA official match schedule PDF grid. API-Football id included only when already verified in UFO Predictor.",
  },
  {
    fixtureKey: "wc2026-match-007",
    matchNumber: 7,
    matchSlug: "world-cup-2026-brazil-vs-morocco-2026-06-13",
    stage: "group_stage",
    groupKey: "group-c",
    roundLabel: "Group Stage",
    kickoffDateET: "2026-06-13",
    kickoffTimeET: "18:00",
    kickoffAt: "2026-06-13T22:00:00Z",
    timezone: "America/New_York",
    homeTeamKey: "brazil",
    awayTeamKey: "morocco",
    homeTeamFifaCode: "BRA",
    awayTeamFifaCode: "MAR",
    venueKey: "new-york-new-jersey",
    hostCity: "New York New Jersey",
    hostCountry: "USA",
    apiFootballFixtureId: null,
    apiFootballExternalId: null,
    statusHint: "scheduled",
    sourceNotes:
      "Extracted from FIFA official match schedule PDF grid. API-Football id included only when already verified in UFO Predictor.",
  },
  {
    fixtureKey: "wc2026-match-008",
    matchNumber: 8,
    matchSlug: "world-cup-2026-qatar-vs-switzerland-2026-06-13",
    stage: "group_stage",
    groupKey: "group-b",
    roundLabel: "Group Stage",
    kickoffDateET: "2026-06-13",
    kickoffTimeET: "15:00",
    kickoffAt: "2026-06-13T19:00:00Z",
    timezone: "America/New_York",
    homeTeamKey: "qatar",
    awayTeamKey: "switzerland",
    homeTeamFifaCode: "QAT",
    awayTeamFifaCode: "SUI",
    venueKey: "san-francisco-bay-area",
    hostCity: "San Francisco Bay Area",
    hostCountry: "USA",
    apiFootballFixtureId: null,
    apiFootballExternalId: null,
    statusHint: "scheduled",
    sourceNotes:
      "Extracted from FIFA official match schedule PDF grid. API-Football id included only when already verified in UFO Predictor.",
  },
  {
    fixtureKey: "wc2026-match-009",
    matchNumber: 9,
    matchSlug: "world-cup-2026-cote-divoire-vs-ecuador-2026-06-14",
    stage: "group_stage",
    groupKey: "group-e",
    roundLabel: "Group Stage",
    kickoffDateET: "2026-06-14",
    kickoffTimeET: "19:00",
    kickoffAt: "2026-06-14T23:00:00Z",
    timezone: "America/New_York",
    homeTeamKey: "cote-divoire",
    awayTeamKey: "ecuador",
    homeTeamFifaCode: "CIV",
    awayTeamFifaCode: "ECU",
    venueKey: "philadelphia",
    hostCity: "Philadelphia",
    hostCountry: "USA",
    apiFootballFixtureId: null,
    apiFootballExternalId: null,
    statusHint: "scheduled",
    sourceNotes:
      "Extracted from FIFA official match schedule PDF grid. API-Football id included only when already verified in UFO Predictor.",
  },
  {
    fixtureKey: "wc2026-match-010",
    matchNumber: 10,
    matchSlug: "world-cup-2026-germany-vs-curacao-2026-06-14",
    stage: "group_stage",
    groupKey: "group-e",
    roundLabel: "Group Stage",
    kickoffDateET: "2026-06-14",
    kickoffTimeET: "13:00",
    kickoffAt: "2026-06-14T17:00:00Z",
    timezone: "America/New_York",
    homeTeamKey: "germany",
    awayTeamKey: "curacao",
    homeTeamFifaCode: "GER",
    awayTeamFifaCode: "CUW",
    venueKey: "houston",
    hostCity: "Houston",
    hostCountry: "USA",
    apiFootballFixtureId: null,
    apiFootballExternalId: null,
    statusHint: "scheduled",
    sourceNotes:
      "Extracted from FIFA official match schedule PDF grid. API-Football id included only when already verified in UFO Predictor.",
  },
  {
    fixtureKey: "wc2026-match-011",
    matchNumber: 11,
    matchSlug: "world-cup-2026-netherlands-vs-japan-2026-06-14",
    stage: "group_stage",
    groupKey: "group-f",
    roundLabel: "Group Stage",
    kickoffDateET: "2026-06-14",
    kickoffTimeET: "16:00",
    kickoffAt: "2026-06-14T20:00:00Z",
    timezone: "America/New_York",
    homeTeamKey: "netherlands",
    awayTeamKey: "japan",
    homeTeamFifaCode: "NED",
    awayTeamFifaCode: "JPN",
    venueKey: "dallas",
    hostCity: "Dallas",
    hostCountry: "USA",
    apiFootballFixtureId: null,
    apiFootballExternalId: null,
    statusHint: "scheduled",
    sourceNotes:
      "Extracted from FIFA official match schedule PDF grid. API-Football id included only when already verified in UFO Predictor.",
  },
  {
    fixtureKey: "wc2026-match-012",
    matchNumber: 12,
    matchSlug: "world-cup-2026-sweden-vs-tunisia-2026-06-15",
    stage: "group_stage",
    groupKey: "group-f",
    roundLabel: "Group Stage",
    kickoffDateET: "2026-06-14",
    kickoffTimeET: "22:00",
    kickoffAt: "2026-06-15T02:00:00Z",
    timezone: "America/New_York",
    homeTeamKey: "sweden",
    awayTeamKey: "tunisia",
    homeTeamFifaCode: "SWE",
    awayTeamFifaCode: "TUN",
    venueKey: "monterrey",
    hostCity: "Monterrey",
    hostCountry: "Mexico",
    apiFootballFixtureId: null,
    apiFootballExternalId: null,
    statusHint: "scheduled",
    sourceNotes:
      "Extracted from FIFA official match schedule PDF grid. API-Football id included only when already verified in UFO Predictor.",
  },
  {
    fixtureKey: "wc2026-match-013",
    matchNumber: 13,
    matchSlug: "world-cup-2026-saudi-arabia-vs-uruguay-2026-06-15",
    stage: "group_stage",
    groupKey: "group-h",
    roundLabel: "Group Stage",
    kickoffDateET: "2026-06-15",
    kickoffTimeET: "18:00",
    kickoffAt: "2026-06-15T22:00:00Z",
    timezone: "America/New_York",
    homeTeamKey: "saudi-arabia",
    awayTeamKey: "uruguay",
    homeTeamFifaCode: "KSA",
    awayTeamFifaCode: "URU",
    venueKey: "miami",
    hostCity: "Miami",
    hostCountry: "USA",
    apiFootballFixtureId: null,
    apiFootballExternalId: null,
    statusHint: "scheduled",
    sourceNotes:
      "Extracted from FIFA official match schedule PDF grid. API-Football id included only when already verified in UFO Predictor.",
  },
  {
    fixtureKey: "wc2026-match-014",
    matchNumber: 14,
    matchSlug: "world-cup-2026-spain-vs-cabo-verde-2026-06-15",
    stage: "group_stage",
    groupKey: "group-h",
    roundLabel: "Group Stage",
    kickoffDateET: "2026-06-15",
    kickoffTimeET: "12:00",
    kickoffAt: "2026-06-15T16:00:00Z",
    timezone: "America/New_York",
    homeTeamKey: "spain",
    awayTeamKey: "cabo-verde",
    homeTeamFifaCode: "ESP",
    awayTeamFifaCode: "CPV",
    venueKey: "atlanta",
    hostCity: "Atlanta",
    hostCountry: "USA",
    apiFootballFixtureId: null,
    apiFootballExternalId: null,
    statusHint: "scheduled",
    sourceNotes:
      "Extracted from FIFA official match schedule PDF grid. API-Football id included only when already verified in UFO Predictor.",
  },
  {
    fixtureKey: "wc2026-match-015",
    matchNumber: 15,
    matchSlug: "world-cup-2026-iran-vs-new-zealand-2026-06-16",
    stage: "group_stage",
    groupKey: "group-g",
    roundLabel: "Group Stage",
    kickoffDateET: "2026-06-15",
    kickoffTimeET: "21:00",
    kickoffAt: "2026-06-16T01:00:00Z",
    timezone: "America/New_York",
    homeTeamKey: "iran",
    awayTeamKey: "new-zealand",
    homeTeamFifaCode: "IRN",
    awayTeamFifaCode: "NZL",
    venueKey: "los-angeles",
    hostCity: "Los Angeles",
    hostCountry: "USA",
    apiFootballFixtureId: null,
    apiFootballExternalId: null,
    statusHint: "scheduled",
    sourceNotes:
      "Extracted from FIFA official match schedule PDF grid. API-Football id included only when already verified in UFO Predictor.",
  },
  {
    fixtureKey: "wc2026-match-016",
    matchNumber: 16,
    matchSlug: "world-cup-2026-belgium-vs-egypt-2026-06-15",
    stage: "group_stage",
    groupKey: "group-g",
    roundLabel: "Group Stage",
    kickoffDateET: "2026-06-15",
    kickoffTimeET: "15:00",
    kickoffAt: "2026-06-15T19:00:00Z",
    timezone: "America/New_York",
    homeTeamKey: "belgium",
    awayTeamKey: "egypt",
    homeTeamFifaCode: "BEL",
    awayTeamFifaCode: "EGY",
    venueKey: "seattle",
    hostCity: "Seattle",
    hostCountry: "USA",
    apiFootballFixtureId: null,
    apiFootballExternalId: null,
    statusHint: "scheduled",
    sourceNotes:
      "Extracted from FIFA official match schedule PDF grid. API-Football id included only when already verified in UFO Predictor.",
  },
  {
    fixtureKey: "wc2026-match-017",
    matchNumber: 17,
    matchSlug: "world-cup-2026-france-vs-senegal-2026-06-16",
    stage: "group_stage",
    groupKey: "group-i",
    roundLabel: "Group Stage",
    kickoffDateET: "2026-06-16",
    kickoffTimeET: "15:00",
    kickoffAt: "2026-06-16T19:00:00Z",
    timezone: "America/New_York",
    homeTeamKey: "france",
    awayTeamKey: "senegal",
    homeTeamFifaCode: "FRA",
    awayTeamFifaCode: "SEN",
    venueKey: "new-york-new-jersey",
    hostCity: "New York New Jersey",
    hostCountry: "USA",
    apiFootballFixtureId: null,
    apiFootballExternalId: null,
    statusHint: "scheduled",
    sourceNotes:
      "Extracted from FIFA official match schedule PDF grid. API-Football id included only when already verified in UFO Predictor.",
  },
  {
    fixtureKey: "wc2026-match-018",
    matchNumber: 18,
    matchSlug: "world-cup-2026-iraq-vs-norway-2026-06-16",
    stage: "group_stage",
    groupKey: "group-i",
    roundLabel: "Group Stage",
    kickoffDateET: "2026-06-16",
    kickoffTimeET: "18:00",
    kickoffAt: "2026-06-16T22:00:00Z",
    timezone: "America/New_York",
    homeTeamKey: "iraq",
    awayTeamKey: "norway",
    homeTeamFifaCode: "IRQ",
    awayTeamFifaCode: "NOR",
    venueKey: "boston",
    hostCity: "Boston",
    hostCountry: "USA",
    apiFootballFixtureId: null,
    apiFootballExternalId: null,
    statusHint: "scheduled",
    sourceNotes:
      "Extracted from FIFA official match schedule PDF grid. API-Football id included only when already verified in UFO Predictor.",
  },
  {
    fixtureKey: "wc2026-match-019",
    matchNumber: 19,
    matchSlug: "world-cup-2026-argentina-vs-algeria-2026-06-17",
    stage: "group_stage",
    groupKey: "group-j",
    roundLabel: "Group Stage",
    kickoffDateET: "2026-06-16",
    kickoffTimeET: "21:00",
    kickoffAt: "2026-06-17T01:00:00Z",
    timezone: "America/New_York",
    homeTeamKey: "argentina",
    awayTeamKey: "algeria",
    homeTeamFifaCode: "ARG",
    awayTeamFifaCode: "ALG",
    venueKey: "kansas-city",
    hostCity: "Kansas City",
    hostCountry: "USA",
    apiFootballFixtureId: null,
    apiFootballExternalId: null,
    statusHint: "scheduled",
    sourceNotes:
      "Extracted from FIFA official match schedule PDF grid. API-Football id included only when already verified in UFO Predictor.",
  },
  {
    fixtureKey: "wc2026-match-020",
    matchNumber: 20,
    matchSlug: "world-cup-2026-austria-vs-jordan-2026-06-16",
    stage: "group_stage",
    groupKey: "group-j",
    roundLabel: "Group Stage",
    kickoffDateET: "2026-06-16",
    kickoffTimeET: "00:00",
    kickoffAt: "2026-06-16T04:00:00Z",
    timezone: "America/New_York",
    homeTeamKey: "austria",
    awayTeamKey: "jordan",
    homeTeamFifaCode: "AUT",
    awayTeamFifaCode: "JOR",
    venueKey: "san-francisco-bay-area",
    hostCity: "San Francisco Bay Area",
    hostCountry: "USA",
    apiFootballFixtureId: null,
    apiFootballExternalId: null,
    statusHint: "scheduled",
    sourceNotes:
      "Extracted from FIFA official match schedule PDF grid. API-Football id included only when already verified in UFO Predictor.",
  },
  {
    fixtureKey: "wc2026-match-021",
    matchNumber: 21,
    matchSlug: "world-cup-2026-ghana-vs-panama-2026-06-17",
    stage: "group_stage",
    groupKey: "group-l",
    roundLabel: "Group Stage",
    kickoffDateET: "2026-06-17",
    kickoffTimeET: "19:00",
    kickoffAt: "2026-06-17T23:00:00Z",
    timezone: "America/New_York",
    homeTeamKey: "ghana",
    awayTeamKey: "panama",
    homeTeamFifaCode: "GHA",
    awayTeamFifaCode: "PAN",
    venueKey: "toronto",
    hostCity: "Toronto",
    hostCountry: "Canada",
    apiFootballFixtureId: null,
    apiFootballExternalId: null,
    statusHint: "scheduled",
    sourceNotes:
      "Extracted from FIFA official match schedule PDF grid. API-Football id included only when already verified in UFO Predictor.",
  },
  {
    fixtureKey: "wc2026-match-022",
    matchNumber: 22,
    matchSlug: "world-cup-2026-england-vs-croatia-2026-06-17",
    stage: "group_stage",
    groupKey: "group-l",
    roundLabel: "Group Stage",
    kickoffDateET: "2026-06-17",
    kickoffTimeET: "16:00",
    kickoffAt: "2026-06-17T20:00:00Z",
    timezone: "America/New_York",
    homeTeamKey: "england",
    awayTeamKey: "croatia",
    homeTeamFifaCode: "ENG",
    awayTeamFifaCode: "CRO",
    venueKey: "dallas",
    hostCity: "Dallas",
    hostCountry: "USA",
    apiFootballFixtureId: null,
    apiFootballExternalId: null,
    statusHint: "scheduled",
    sourceNotes:
      "Extracted from FIFA official match schedule PDF grid. API-Football id included only when already verified in UFO Predictor.",
  },
  {
    fixtureKey: "wc2026-match-023",
    matchNumber: 23,
    matchSlug: "world-cup-2026-portugal-vs-congo-dr-2026-06-17",
    stage: "group_stage",
    groupKey: "group-k",
    roundLabel: "Group Stage",
    kickoffDateET: "2026-06-17",
    kickoffTimeET: "13:00",
    kickoffAt: "2026-06-17T17:00:00Z",
    timezone: "America/New_York",
    homeTeamKey: "portugal",
    awayTeamKey: "congo-dr",
    homeTeamFifaCode: "POR",
    awayTeamFifaCode: "COD",
    venueKey: "houston",
    hostCity: "Houston",
    hostCountry: "USA",
    apiFootballFixtureId: null,
    apiFootballExternalId: null,
    statusHint: "scheduled",
    sourceNotes:
      "Extracted from FIFA official match schedule PDF grid. API-Football id included only when already verified in UFO Predictor.",
  },
  {
    fixtureKey: "wc2026-match-024",
    matchNumber: 24,
    matchSlug: "world-cup-2026-uzbekistan-vs-colombia-2026-06-18",
    stage: "group_stage",
    groupKey: "group-k",
    roundLabel: "Group Stage",
    kickoffDateET: "2026-06-17",
    kickoffTimeET: "22:00",
    kickoffAt: "2026-06-18T02:00:00Z",
    timezone: "America/New_York",
    homeTeamKey: "uzbekistan",
    awayTeamKey: "colombia",
    homeTeamFifaCode: "UZB",
    awayTeamFifaCode: "COL",
    venueKey: "mexico-city",
    hostCity: "Mexico City",
    hostCountry: "Mexico",
    apiFootballFixtureId: null,
    apiFootballExternalId: null,
    statusHint: "scheduled",
    sourceNotes:
      "Extracted from FIFA official match schedule PDF grid. API-Football id included only when already verified in UFO Predictor.",
  },
  {
    fixtureKey: "wc2026-match-025",
    matchNumber: 25,
    matchSlug: "world-cup-2026-czech-republic-vs-south-africa-2026-06-18",
    stage: "group_stage",
    groupKey: "group-a",
    roundLabel: "Group Stage",
    kickoffDateET: "2026-06-18",
    kickoffTimeET: "12:00",
    kickoffAt: "2026-06-18T16:00:00Z",
    timezone: "America/New_York",
    homeTeamKey: "czech-republic",
    awayTeamKey: "south-africa",
    homeTeamFifaCode: "CZE",
    awayTeamFifaCode: "RSA",
    venueKey: "atlanta",
    hostCity: "Atlanta",
    hostCountry: "USA",
    apiFootballFixtureId: null,
    apiFootballExternalId: null,
    statusHint: "scheduled",
    sourceNotes:
      "Extracted from FIFA official match schedule PDF grid. API-Football id included only when already verified in UFO Predictor.",
  },
  {
    fixtureKey: "wc2026-match-026",
    matchNumber: 26,
    matchSlug: "world-cup-2026-switzerland-vs-bosnia-herzegovina-2026-06-18",
    stage: "group_stage",
    groupKey: "group-b",
    roundLabel: "Group Stage",
    kickoffDateET: "2026-06-18",
    kickoffTimeET: "15:00",
    kickoffAt: "2026-06-18T19:00:00Z",
    timezone: "America/New_York",
    homeTeamKey: "switzerland",
    awayTeamKey: "bosnia-herzegovina",
    homeTeamFifaCode: "SUI",
    awayTeamFifaCode: "BIH",
    venueKey: "los-angeles",
    hostCity: "Los Angeles",
    hostCountry: "USA",
    apiFootballFixtureId: null,
    apiFootballExternalId: null,
    statusHint: "scheduled",
    sourceNotes:
      "Extracted from FIFA official match schedule PDF grid. API-Football id included only when already verified in UFO Predictor.",
  },
  {
    fixtureKey: "wc2026-match-027",
    matchNumber: 27,
    matchSlug: "world-cup-2026-canada-vs-qatar-2026-06-18",
    stage: "group_stage",
    groupKey: "group-b",
    roundLabel: "Group Stage",
    kickoffDateET: "2026-06-18",
    kickoffTimeET: "18:00",
    kickoffAt: "2026-06-18T22:00:00Z",
    timezone: "America/New_York",
    homeTeamKey: "canada",
    awayTeamKey: "qatar",
    homeTeamFifaCode: "CAN",
    awayTeamFifaCode: "QAT",
    venueKey: "vancouver",
    hostCity: "Vancouver",
    hostCountry: "Canada",
    apiFootballFixtureId: null,
    apiFootballExternalId: null,
    statusHint: "scheduled",
    sourceNotes:
      "Extracted from FIFA official match schedule PDF grid. API-Football id included only when already verified in UFO Predictor.",
  },
  {
    fixtureKey: "wc2026-match-028",
    matchNumber: 28,
    matchSlug: "world-cup-2026-mexico-vs-south-korea-2026-06-19",
    stage: "group_stage",
    groupKey: "group-a",
    roundLabel: "Group Stage",
    kickoffDateET: "2026-06-18",
    kickoffTimeET: "21:00",
    kickoffAt: "2026-06-19T01:00:00Z",
    timezone: "America/New_York",
    homeTeamKey: "mexico",
    awayTeamKey: "south-korea",
    homeTeamFifaCode: "MEX",
    awayTeamFifaCode: "KOR",
    venueKey: "guadalajara",
    hostCity: "Guadalajara",
    hostCountry: "Mexico",
    apiFootballFixtureId: null,
    apiFootballExternalId: null,
    statusHint: "scheduled",
    sourceNotes:
      "Extracted from FIFA official match schedule PDF grid. API-Football id included only when already verified in UFO Predictor.",
  },
  {
    fixtureKey: "wc2026-match-029",
    matchNumber: 29,
    matchSlug: "world-cup-2026-brazil-vs-haiti-2026-06-20",
    stage: "group_stage",
    groupKey: "group-c",
    roundLabel: "Group Stage",
    kickoffDateET: "2026-06-19",
    kickoffTimeET: "20:30",
    kickoffAt: "2026-06-20T00:30:00Z",
    timezone: "America/New_York",
    homeTeamKey: "brazil",
    awayTeamKey: "haiti",
    homeTeamFifaCode: "BRA",
    awayTeamFifaCode: "HAI",
    venueKey: "philadelphia",
    hostCity: "Philadelphia",
    hostCountry: "USA",
    apiFootballFixtureId: null,
    apiFootballExternalId: null,
    statusHint: "scheduled",
    sourceNotes:
      "Extracted from FIFA official match schedule PDF grid. API-Football id included only when already verified in UFO Predictor.",
  },
  {
    fixtureKey: "wc2026-match-030",
    matchNumber: 30,
    matchSlug: "world-cup-2026-scotland-vs-morocco-2026-06-19",
    stage: "group_stage",
    groupKey: "group-c",
    roundLabel: "Group Stage",
    kickoffDateET: "2026-06-19",
    kickoffTimeET: "18:00",
    kickoffAt: "2026-06-19T22:00:00Z",
    timezone: "America/New_York",
    homeTeamKey: "scotland",
    awayTeamKey: "morocco",
    homeTeamFifaCode: "SCO",
    awayTeamFifaCode: "MAR",
    venueKey: "boston",
    hostCity: "Boston",
    hostCountry: "USA",
    apiFootballFixtureId: null,
    apiFootballExternalId: null,
    statusHint: "scheduled",
    sourceNotes:
      "Extracted from FIFA official match schedule PDF grid. API-Football id included only when already verified in UFO Predictor.",
  },
  {
    fixtureKey: "wc2026-match-031",
    matchNumber: 31,
    matchSlug: "world-cup-2026-turkiye-vs-paraguay-2026-06-20",
    stage: "group_stage",
    groupKey: "group-d",
    roundLabel: "Group Stage",
    kickoffDateET: "2026-06-19",
    kickoffTimeET: "23:00",
    kickoffAt: "2026-06-20T03:00:00Z",
    timezone: "America/New_York",
    homeTeamKey: "turkiye",
    awayTeamKey: "paraguay",
    homeTeamFifaCode: "TUR",
    awayTeamFifaCode: "PAR",
    venueKey: "san-francisco-bay-area",
    hostCity: "San Francisco Bay Area",
    hostCountry: "USA",
    apiFootballFixtureId: null,
    apiFootballExternalId: null,
    statusHint: "scheduled",
    sourceNotes:
      "Extracted from FIFA official match schedule PDF grid. API-Football id included only when already verified in UFO Predictor.",
  },
  {
    fixtureKey: "wc2026-match-032",
    matchNumber: 32,
    matchSlug: "world-cup-2026-usa-vs-australia-2026-06-19",
    stage: "group_stage",
    groupKey: "group-d",
    roundLabel: "Group Stage",
    kickoffDateET: "2026-06-19",
    kickoffTimeET: "15:00",
    kickoffAt: "2026-06-19T19:00:00Z",
    timezone: "America/New_York",
    homeTeamKey: "usa",
    awayTeamKey: "australia",
    homeTeamFifaCode: "USA",
    awayTeamFifaCode: "AUS",
    venueKey: "seattle",
    hostCity: "Seattle",
    hostCountry: "USA",
    apiFootballFixtureId: null,
    apiFootballExternalId: null,
    statusHint: "scheduled",
    sourceNotes:
      "Extracted from FIFA official match schedule PDF grid. API-Football id included only when already verified in UFO Predictor.",
  },
  {
    fixtureKey: "wc2026-match-033",
    matchNumber: 33,
    matchSlug: "world-cup-2026-germany-vs-cote-divoire-2026-06-20",
    stage: "group_stage",
    groupKey: "group-e",
    roundLabel: "Group Stage",
    kickoffDateET: "2026-06-20",
    kickoffTimeET: "16:00",
    kickoffAt: "2026-06-20T20:00:00Z",
    timezone: "America/New_York",
    homeTeamKey: "germany",
    awayTeamKey: "cote-divoire",
    homeTeamFifaCode: "GER",
    awayTeamFifaCode: "CIV",
    venueKey: "toronto",
    hostCity: "Toronto",
    hostCountry: "Canada",
    apiFootballFixtureId: null,
    apiFootballExternalId: null,
    statusHint: "scheduled",
    sourceNotes:
      "Extracted from FIFA official match schedule PDF grid. API-Football id included only when already verified in UFO Predictor.",
  },
  {
    fixtureKey: "wc2026-match-034",
    matchNumber: 34,
    matchSlug: "world-cup-2026-ecuador-vs-curacao-2026-06-21",
    stage: "group_stage",
    groupKey: "group-e",
    roundLabel: "Group Stage",
    kickoffDateET: "2026-06-20",
    kickoffTimeET: "20:00",
    kickoffAt: "2026-06-21T00:00:00Z",
    timezone: "America/New_York",
    homeTeamKey: "ecuador",
    awayTeamKey: "curacao",
    homeTeamFifaCode: "ECU",
    awayTeamFifaCode: "CUW",
    venueKey: "kansas-city",
    hostCity: "Kansas City",
    hostCountry: "USA",
    apiFootballFixtureId: null,
    apiFootballExternalId: null,
    statusHint: "scheduled",
    sourceNotes:
      "Extracted from FIFA official match schedule PDF grid. API-Football id included only when already verified in UFO Predictor.",
  },
  {
    fixtureKey: "wc2026-match-035",
    matchNumber: 35,
    matchSlug: "world-cup-2026-netherlands-vs-sweden-2026-06-20",
    stage: "group_stage",
    groupKey: "group-f",
    roundLabel: "Group Stage",
    kickoffDateET: "2026-06-20",
    kickoffTimeET: "13:00",
    kickoffAt: "2026-06-20T17:00:00Z",
    timezone: "America/New_York",
    homeTeamKey: "netherlands",
    awayTeamKey: "sweden",
    homeTeamFifaCode: "NED",
    awayTeamFifaCode: "SWE",
    venueKey: "houston",
    hostCity: "Houston",
    hostCountry: "USA",
    apiFootballFixtureId: null,
    apiFootballExternalId: null,
    statusHint: "scheduled",
    sourceNotes:
      "Extracted from FIFA official match schedule PDF grid. API-Football id included only when already verified in UFO Predictor.",
  },
  {
    fixtureKey: "wc2026-match-036",
    matchNumber: 36,
    matchSlug: "world-cup-2026-tunisia-vs-japan-2026-06-20",
    stage: "group_stage",
    groupKey: "group-f",
    roundLabel: "Group Stage",
    kickoffDateET: "2026-06-20",
    kickoffTimeET: "00:00",
    kickoffAt: "2026-06-20T04:00:00Z",
    timezone: "America/New_York",
    homeTeamKey: "tunisia",
    awayTeamKey: "japan",
    homeTeamFifaCode: "TUN",
    awayTeamFifaCode: "JPN",
    venueKey: "monterrey",
    hostCity: "Monterrey",
    hostCountry: "Mexico",
    apiFootballFixtureId: null,
    apiFootballExternalId: null,
    statusHint: "scheduled",
    sourceNotes:
      "Extracted from FIFA official match schedule PDF grid. API-Football id included only when already verified in UFO Predictor.",
  },
  {
    fixtureKey: "wc2026-match-037",
    matchNumber: 37,
    matchSlug: "world-cup-2026-uruguay-vs-cabo-verde-2026-06-21",
    stage: "group_stage",
    groupKey: "group-h",
    roundLabel: "Group Stage",
    kickoffDateET: "2026-06-21",
    kickoffTimeET: "18:00",
    kickoffAt: "2026-06-21T22:00:00Z",
    timezone: "America/New_York",
    homeTeamKey: "uruguay",
    awayTeamKey: "cabo-verde",
    homeTeamFifaCode: "URU",
    awayTeamFifaCode: "CPV",
    venueKey: "miami",
    hostCity: "Miami",
    hostCountry: "USA",
    apiFootballFixtureId: null,
    apiFootballExternalId: null,
    statusHint: "scheduled",
    sourceNotes:
      "Extracted from FIFA official match schedule PDF grid. API-Football id included only when already verified in UFO Predictor.",
  },
  {
    fixtureKey: "wc2026-match-038",
    matchNumber: 38,
    matchSlug: "world-cup-2026-spain-vs-saudi-arabia-2026-06-21",
    stage: "group_stage",
    groupKey: "group-h",
    roundLabel: "Group Stage",
    kickoffDateET: "2026-06-21",
    kickoffTimeET: "12:00",
    kickoffAt: "2026-06-21T16:00:00Z",
    timezone: "America/New_York",
    homeTeamKey: "spain",
    awayTeamKey: "saudi-arabia",
    homeTeamFifaCode: "ESP",
    awayTeamFifaCode: "KSA",
    venueKey: "atlanta",
    hostCity: "Atlanta",
    hostCountry: "USA",
    apiFootballFixtureId: null,
    apiFootballExternalId: null,
    statusHint: "scheduled",
    sourceNotes:
      "Extracted from FIFA official match schedule PDF grid. API-Football id included only when already verified in UFO Predictor.",
  },
  {
    fixtureKey: "wc2026-match-039",
    matchNumber: 39,
    matchSlug: "world-cup-2026-belgium-vs-iran-2026-06-21",
    stage: "group_stage",
    groupKey: "group-g",
    roundLabel: "Group Stage",
    kickoffDateET: "2026-06-21",
    kickoffTimeET: "15:00",
    kickoffAt: "2026-06-21T19:00:00Z",
    timezone: "America/New_York",
    homeTeamKey: "belgium",
    awayTeamKey: "iran",
    homeTeamFifaCode: "BEL",
    awayTeamFifaCode: "IRN",
    venueKey: "los-angeles",
    hostCity: "Los Angeles",
    hostCountry: "USA",
    apiFootballFixtureId: null,
    apiFootballExternalId: null,
    statusHint: "scheduled",
    sourceNotes:
      "Extracted from FIFA official match schedule PDF grid. API-Football id included only when already verified in UFO Predictor.",
  },
  {
    fixtureKey: "wc2026-match-040",
    matchNumber: 40,
    matchSlug: "world-cup-2026-new-zealand-vs-egypt-2026-06-22",
    stage: "group_stage",
    groupKey: "group-g",
    roundLabel: "Group Stage",
    kickoffDateET: "2026-06-21",
    kickoffTimeET: "21:00",
    kickoffAt: "2026-06-22T01:00:00Z",
    timezone: "America/New_York",
    homeTeamKey: "new-zealand",
    awayTeamKey: "egypt",
    homeTeamFifaCode: "NZL",
    awayTeamFifaCode: "EGY",
    venueKey: "vancouver",
    hostCity: "Vancouver",
    hostCountry: "Canada",
    apiFootballFixtureId: null,
    apiFootballExternalId: null,
    statusHint: "scheduled",
    sourceNotes:
      "Extracted from FIFA official match schedule PDF grid. API-Football id included only when already verified in UFO Predictor.",
  },
  {
    fixtureKey: "wc2026-match-041",
    matchNumber: 41,
    matchSlug: "world-cup-2026-norway-vs-senegal-2026-06-23",
    stage: "group_stage",
    groupKey: "group-i",
    roundLabel: "Group Stage",
    kickoffDateET: "2026-06-22",
    kickoffTimeET: "20:00",
    kickoffAt: "2026-06-23T00:00:00Z",
    timezone: "America/New_York",
    homeTeamKey: "norway",
    awayTeamKey: "senegal",
    homeTeamFifaCode: "NOR",
    awayTeamFifaCode: "SEN",
    venueKey: "new-york-new-jersey",
    hostCity: "New York New Jersey",
    hostCountry: "USA",
    apiFootballFixtureId: null,
    apiFootballExternalId: null,
    statusHint: "scheduled",
    sourceNotes:
      "Extracted from FIFA official match schedule PDF grid. API-Football id included only when already verified in UFO Predictor.",
  },
  {
    fixtureKey: "wc2026-match-042",
    matchNumber: 42,
    matchSlug: "world-cup-2026-france-vs-iraq-2026-06-22",
    stage: "group_stage",
    groupKey: "group-i",
    roundLabel: "Group Stage",
    kickoffDateET: "2026-06-22",
    kickoffTimeET: "17:00",
    kickoffAt: "2026-06-22T21:00:00Z",
    timezone: "America/New_York",
    homeTeamKey: "france",
    awayTeamKey: "iraq",
    homeTeamFifaCode: "FRA",
    awayTeamFifaCode: "IRQ",
    venueKey: "philadelphia",
    hostCity: "Philadelphia",
    hostCountry: "USA",
    apiFootballFixtureId: null,
    apiFootballExternalId: null,
    statusHint: "scheduled",
    sourceNotes:
      "Extracted from FIFA official match schedule PDF grid. API-Football id included only when already verified in UFO Predictor.",
  },
  {
    fixtureKey: "wc2026-match-043",
    matchNumber: 43,
    matchSlug: "world-cup-2026-argentina-vs-austria-2026-06-22",
    stage: "group_stage",
    groupKey: "group-j",
    roundLabel: "Group Stage",
    kickoffDateET: "2026-06-22",
    kickoffTimeET: "13:00",
    kickoffAt: "2026-06-22T17:00:00Z",
    timezone: "America/New_York",
    homeTeamKey: "argentina",
    awayTeamKey: "austria",
    homeTeamFifaCode: "ARG",
    awayTeamFifaCode: "AUT",
    venueKey: "dallas",
    hostCity: "Dallas",
    hostCountry: "USA",
    apiFootballFixtureId: null,
    apiFootballExternalId: null,
    statusHint: "scheduled",
    sourceNotes:
      "Extracted from FIFA official match schedule PDF grid. API-Football id included only when already verified in UFO Predictor.",
  },
  {
    fixtureKey: "wc2026-match-044",
    matchNumber: 44,
    matchSlug: "world-cup-2026-jordan-vs-algeria-2026-06-23",
    stage: "group_stage",
    groupKey: "group-j",
    roundLabel: "Group Stage",
    kickoffDateET: "2026-06-22",
    kickoffTimeET: "23:00",
    kickoffAt: "2026-06-23T03:00:00Z",
    timezone: "America/New_York",
    homeTeamKey: "jordan",
    awayTeamKey: "algeria",
    homeTeamFifaCode: "JOR",
    awayTeamFifaCode: "ALG",
    venueKey: "san-francisco-bay-area",
    hostCity: "San Francisco Bay Area",
    hostCountry: "USA",
    apiFootballFixtureId: null,
    apiFootballExternalId: null,
    statusHint: "scheduled",
    sourceNotes:
      "Extracted from FIFA official match schedule PDF grid. API-Football id included only when already verified in UFO Predictor.",
  },
  {
    fixtureKey: "wc2026-match-045",
    matchNumber: 45,
    matchSlug: "world-cup-2026-england-vs-ghana-2026-06-23",
    stage: "group_stage",
    groupKey: "group-l",
    roundLabel: "Group Stage",
    kickoffDateET: "2026-06-23",
    kickoffTimeET: "16:00",
    kickoffAt: "2026-06-23T20:00:00Z",
    timezone: "America/New_York",
    homeTeamKey: "england",
    awayTeamKey: "ghana",
    homeTeamFifaCode: "ENG",
    awayTeamFifaCode: "GHA",
    venueKey: "boston",
    hostCity: "Boston",
    hostCountry: "USA",
    apiFootballFixtureId: null,
    apiFootballExternalId: null,
    statusHint: "scheduled",
    sourceNotes:
      "Extracted from FIFA official match schedule PDF grid. API-Football id included only when already verified in UFO Predictor.",
  },
  {
    fixtureKey: "wc2026-match-046",
    matchNumber: 46,
    matchSlug: "world-cup-2026-panama-vs-croatia-2026-06-23",
    stage: "group_stage",
    groupKey: "group-l",
    roundLabel: "Group Stage",
    kickoffDateET: "2026-06-23",
    kickoffTimeET: "19:00",
    kickoffAt: "2026-06-23T23:00:00Z",
    timezone: "America/New_York",
    homeTeamKey: "panama",
    awayTeamKey: "croatia",
    homeTeamFifaCode: "PAN",
    awayTeamFifaCode: "CRO",
    venueKey: "toronto",
    hostCity: "Toronto",
    hostCountry: "Canada",
    apiFootballFixtureId: null,
    apiFootballExternalId: null,
    statusHint: "scheduled",
    sourceNotes:
      "Extracted from FIFA official match schedule PDF grid. API-Football id included only when already verified in UFO Predictor.",
  },
  {
    fixtureKey: "wc2026-match-047",
    matchNumber: 47,
    matchSlug: "world-cup-2026-portugal-vs-uzbekistan-2026-06-23",
    stage: "group_stage",
    groupKey: "group-k",
    roundLabel: "Group Stage",
    kickoffDateET: "2026-06-23",
    kickoffTimeET: "13:00",
    kickoffAt: "2026-06-23T17:00:00Z",
    timezone: "America/New_York",
    homeTeamKey: "portugal",
    awayTeamKey: "uzbekistan",
    homeTeamFifaCode: "POR",
    awayTeamFifaCode: "UZB",
    venueKey: "houston",
    hostCity: "Houston",
    hostCountry: "USA",
    apiFootballFixtureId: null,
    apiFootballExternalId: null,
    statusHint: "scheduled",
    sourceNotes:
      "Extracted from FIFA official match schedule PDF grid. API-Football id included only when already verified in UFO Predictor.",
  },
  {
    fixtureKey: "wc2026-match-048",
    matchNumber: 48,
    matchSlug: "world-cup-2026-colombia-vs-congo-dr-2026-06-24",
    stage: "group_stage",
    groupKey: "group-k",
    roundLabel: "Group Stage",
    kickoffDateET: "2026-06-23",
    kickoffTimeET: "22:00",
    kickoffAt: "2026-06-24T02:00:00Z",
    timezone: "America/New_York",
    homeTeamKey: "colombia",
    awayTeamKey: "congo-dr",
    homeTeamFifaCode: "COL",
    awayTeamFifaCode: "COD",
    venueKey: "guadalajara",
    hostCity: "Guadalajara",
    hostCountry: "Mexico",
    apiFootballFixtureId: null,
    apiFootballExternalId: null,
    statusHint: "scheduled",
    sourceNotes:
      "Extracted from FIFA official match schedule PDF grid. API-Football id included only when already verified in UFO Predictor.",
  },
  {
    fixtureKey: "wc2026-match-049",
    matchNumber: 49,
    matchSlug: "world-cup-2026-scotland-vs-brazil-2026-06-24",
    stage: "group_stage",
    groupKey: "group-c",
    roundLabel: "Group Stage",
    kickoffDateET: "2026-06-24",
    kickoffTimeET: "18:00",
    kickoffAt: "2026-06-24T22:00:00Z",
    timezone: "America/New_York",
    homeTeamKey: "scotland",
    awayTeamKey: "brazil",
    homeTeamFifaCode: "SCO",
    awayTeamFifaCode: "BRA",
    venueKey: "miami",
    hostCity: "Miami",
    hostCountry: "USA",
    apiFootballFixtureId: null,
    apiFootballExternalId: null,
    statusHint: "scheduled",
    sourceNotes:
      "Extracted from FIFA official match schedule PDF grid. API-Football id included only when already verified in UFO Predictor.",
  },
  {
    fixtureKey: "wc2026-match-050",
    matchNumber: 50,
    matchSlug: "world-cup-2026-morocco-vs-haiti-2026-06-24",
    stage: "group_stage",
    groupKey: "group-c",
    roundLabel: "Group Stage",
    kickoffDateET: "2026-06-24",
    kickoffTimeET: "18:00",
    kickoffAt: "2026-06-24T22:00:00Z",
    timezone: "America/New_York",
    homeTeamKey: "morocco",
    awayTeamKey: "haiti",
    homeTeamFifaCode: "MAR",
    awayTeamFifaCode: "HAI",
    venueKey: "atlanta",
    hostCity: "Atlanta",
    hostCountry: "USA",
    apiFootballFixtureId: null,
    apiFootballExternalId: null,
    statusHint: "scheduled",
    sourceNotes:
      "Extracted from FIFA official match schedule PDF grid. API-Football id included only when already verified in UFO Predictor.",
  },
  {
    fixtureKey: "wc2026-match-051",
    matchNumber: 51,
    matchSlug: "world-cup-2026-switzerland-vs-canada-2026-06-24",
    stage: "group_stage",
    groupKey: "group-b",
    roundLabel: "Group Stage",
    kickoffDateET: "2026-06-24",
    kickoffTimeET: "15:00",
    kickoffAt: "2026-06-24T19:00:00Z",
    timezone: "America/New_York",
    homeTeamKey: "switzerland",
    awayTeamKey: "canada",
    homeTeamFifaCode: "SUI",
    awayTeamFifaCode: "CAN",
    venueKey: "vancouver",
    hostCity: "Vancouver",
    hostCountry: "Canada",
    apiFootballFixtureId: null,
    apiFootballExternalId: null,
    statusHint: "scheduled",
    sourceNotes:
      "Extracted from FIFA official match schedule PDF grid. API-Football id included only when already verified in UFO Predictor.",
  },
  {
    fixtureKey: "wc2026-match-052",
    matchNumber: 52,
    matchSlug: "world-cup-2026-bosnia-herzegovina-vs-qatar-2026-06-24",
    stage: "group_stage",
    groupKey: "group-b",
    roundLabel: "Group Stage",
    kickoffDateET: "2026-06-24",
    kickoffTimeET: "15:00",
    kickoffAt: "2026-06-24T19:00:00Z",
    timezone: "America/New_York",
    homeTeamKey: "bosnia-herzegovina",
    awayTeamKey: "qatar",
    homeTeamFifaCode: "BIH",
    awayTeamFifaCode: "QAT",
    venueKey: "seattle",
    hostCity: "Seattle",
    hostCountry: "USA",
    apiFootballFixtureId: null,
    apiFootballExternalId: null,
    statusHint: "scheduled",
    sourceNotes:
      "Extracted from FIFA official match schedule PDF grid. API-Football id included only when already verified in UFO Predictor.",
  },
  {
    fixtureKey: "wc2026-match-053",
    matchNumber: 53,
    matchSlug: "world-cup-2026-czech-republic-vs-mexico-2026-06-25",
    stage: "group_stage",
    groupKey: "group-a",
    roundLabel: "Group Stage",
    kickoffDateET: "2026-06-24",
    kickoffTimeET: "21:00",
    kickoffAt: "2026-06-25T01:00:00Z",
    timezone: "America/New_York",
    homeTeamKey: "czech-republic",
    awayTeamKey: "mexico",
    homeTeamFifaCode: "CZE",
    awayTeamFifaCode: "MEX",
    venueKey: "mexico-city",
    hostCity: "Mexico City",
    hostCountry: "Mexico",
    apiFootballFixtureId: null,
    apiFootballExternalId: null,
    statusHint: "scheduled",
    sourceNotes:
      "Extracted from FIFA official match schedule PDF grid. API-Football id included only when already verified in UFO Predictor.",
  },
  {
    fixtureKey: "wc2026-match-054",
    matchNumber: 54,
    matchSlug: "world-cup-2026-south-africa-vs-south-korea-2026-06-25",
    stage: "group_stage",
    groupKey: "group-a",
    roundLabel: "Group Stage",
    kickoffDateET: "2026-06-24",
    kickoffTimeET: "21:00",
    kickoffAt: "2026-06-25T01:00:00Z",
    timezone: "America/New_York",
    homeTeamKey: "south-africa",
    awayTeamKey: "south-korea",
    homeTeamFifaCode: "RSA",
    awayTeamFifaCode: "KOR",
    venueKey: "monterrey",
    hostCity: "Monterrey",
    hostCountry: "Mexico",
    apiFootballFixtureId: null,
    apiFootballExternalId: null,
    statusHint: "scheduled",
    sourceNotes:
      "Extracted from FIFA official match schedule PDF grid. API-Football id included only when already verified in UFO Predictor.",
  },
  {
    fixtureKey: "wc2026-match-055",
    matchNumber: 55,
    matchSlug: "world-cup-2026-curacao-vs-cote-divoire-2026-06-25",
    stage: "group_stage",
    groupKey: "group-e",
    roundLabel: "Group Stage",
    kickoffDateET: "2026-06-25",
    kickoffTimeET: "16:00",
    kickoffAt: "2026-06-25T20:00:00Z",
    timezone: "America/New_York",
    homeTeamKey: "curacao",
    awayTeamKey: "cote-divoire",
    homeTeamFifaCode: "CUW",
    awayTeamFifaCode: "CIV",
    venueKey: "philadelphia",
    hostCity: "Philadelphia",
    hostCountry: "USA",
    apiFootballFixtureId: null,
    apiFootballExternalId: null,
    statusHint: "scheduled",
    sourceNotes:
      "Extracted from FIFA official match schedule PDF grid. API-Football id included only when already verified in UFO Predictor.",
  },
  {
    fixtureKey: "wc2026-match-056",
    matchNumber: 56,
    matchSlug: "world-cup-2026-ecuador-vs-germany-2026-06-25",
    stage: "group_stage",
    groupKey: "group-e",
    roundLabel: "Group Stage",
    kickoffDateET: "2026-06-25",
    kickoffTimeET: "16:00",
    kickoffAt: "2026-06-25T20:00:00Z",
    timezone: "America/New_York",
    homeTeamKey: "ecuador",
    awayTeamKey: "germany",
    homeTeamFifaCode: "ECU",
    awayTeamFifaCode: "GER",
    venueKey: "new-york-new-jersey",
    hostCity: "New York New Jersey",
    hostCountry: "USA",
    apiFootballFixtureId: null,
    apiFootballExternalId: null,
    statusHint: "scheduled",
    sourceNotes:
      "Extracted from FIFA official match schedule PDF grid. API-Football id included only when already verified in UFO Predictor.",
  },
  {
    fixtureKey: "wc2026-match-057",
    matchNumber: 57,
    matchSlug: "world-cup-2026-japan-vs-sweden-2026-06-25",
    stage: "group_stage",
    groupKey: "group-f",
    roundLabel: "Group Stage",
    kickoffDateET: "2026-06-25",
    kickoffTimeET: "19:00",
    kickoffAt: "2026-06-25T23:00:00Z",
    timezone: "America/New_York",
    homeTeamKey: "japan",
    awayTeamKey: "sweden",
    homeTeamFifaCode: "JPN",
    awayTeamFifaCode: "SWE",
    venueKey: "dallas",
    hostCity: "Dallas",
    hostCountry: "USA",
    apiFootballFixtureId: null,
    apiFootballExternalId: null,
    statusHint: "scheduled",
    sourceNotes:
      "Extracted from FIFA official match schedule PDF grid. API-Football id included only when already verified in UFO Predictor.",
  },
  {
    fixtureKey: "wc2026-match-058",
    matchNumber: 58,
    matchSlug: "world-cup-2026-tunisia-vs-netherlands-2026-06-25",
    stage: "group_stage",
    groupKey: "group-f",
    roundLabel: "Group Stage",
    kickoffDateET: "2026-06-25",
    kickoffTimeET: "19:00",
    kickoffAt: "2026-06-25T23:00:00Z",
    timezone: "America/New_York",
    homeTeamKey: "tunisia",
    awayTeamKey: "netherlands",
    homeTeamFifaCode: "TUN",
    awayTeamFifaCode: "NED",
    venueKey: "kansas-city",
    hostCity: "Kansas City",
    hostCountry: "USA",
    apiFootballFixtureId: null,
    apiFootballExternalId: null,
    statusHint: "scheduled",
    sourceNotes:
      "Extracted from FIFA official match schedule PDF grid. API-Football id included only when already verified in UFO Predictor.",
  },
  {
    fixtureKey: "wc2026-match-059",
    matchNumber: 59,
    matchSlug: "world-cup-2026-turkiye-vs-usa-2026-06-26",
    stage: "group_stage",
    groupKey: "group-d",
    roundLabel: "Group Stage",
    kickoffDateET: "2026-06-25",
    kickoffTimeET: "22:00",
    kickoffAt: "2026-06-26T02:00:00Z",
    timezone: "America/New_York",
    homeTeamKey: "turkiye",
    awayTeamKey: "usa",
    homeTeamFifaCode: "TUR",
    awayTeamFifaCode: "USA",
    venueKey: "los-angeles",
    hostCity: "Los Angeles",
    hostCountry: "USA",
    apiFootballFixtureId: null,
    apiFootballExternalId: null,
    statusHint: "scheduled",
    sourceNotes:
      "Extracted from FIFA official match schedule PDF grid. API-Football id included only when already verified in UFO Predictor.",
  },
  {
    fixtureKey: "wc2026-match-060",
    matchNumber: 60,
    matchSlug: "world-cup-2026-paraguay-vs-australia-2026-06-26",
    stage: "group_stage",
    groupKey: "group-d",
    roundLabel: "Group Stage",
    kickoffDateET: "2026-06-25",
    kickoffTimeET: "22:00",
    kickoffAt: "2026-06-26T02:00:00Z",
    timezone: "America/New_York",
    homeTeamKey: "paraguay",
    awayTeamKey: "australia",
    homeTeamFifaCode: "PAR",
    awayTeamFifaCode: "AUS",
    venueKey: "san-francisco-bay-area",
    hostCity: "San Francisco Bay Area",
    hostCountry: "USA",
    apiFootballFixtureId: null,
    apiFootballExternalId: null,
    statusHint: "scheduled",
    sourceNotes:
      "Extracted from FIFA official match schedule PDF grid. API-Football id included only when already verified in UFO Predictor.",
  },
  {
    fixtureKey: "wc2026-match-061",
    matchNumber: 61,
    matchSlug: "world-cup-2026-norway-vs-france-2026-06-26",
    stage: "group_stage",
    groupKey: "group-i",
    roundLabel: "Group Stage",
    kickoffDateET: "2026-06-26",
    kickoffTimeET: "15:00",
    kickoffAt: "2026-06-26T19:00:00Z",
    timezone: "America/New_York",
    homeTeamKey: "norway",
    awayTeamKey: "france",
    homeTeamFifaCode: "NOR",
    awayTeamFifaCode: "FRA",
    venueKey: "boston",
    hostCity: "Boston",
    hostCountry: "USA",
    apiFootballFixtureId: null,
    apiFootballExternalId: null,
    statusHint: "scheduled",
    sourceNotes:
      "Extracted from FIFA official match schedule PDF grid. API-Football id included only when already verified in UFO Predictor.",
  },
  {
    fixtureKey: "wc2026-match-062",
    matchNumber: 62,
    matchSlug: "world-cup-2026-senegal-vs-iraq-2026-06-26",
    stage: "group_stage",
    groupKey: "group-i",
    roundLabel: "Group Stage",
    kickoffDateET: "2026-06-26",
    kickoffTimeET: "15:00",
    kickoffAt: "2026-06-26T19:00:00Z",
    timezone: "America/New_York",
    homeTeamKey: "senegal",
    awayTeamKey: "iraq",
    homeTeamFifaCode: "SEN",
    awayTeamFifaCode: "IRQ",
    venueKey: "toronto",
    hostCity: "Toronto",
    hostCountry: "Canada",
    apiFootballFixtureId: null,
    apiFootballExternalId: null,
    statusHint: "scheduled",
    sourceNotes:
      "Extracted from FIFA official match schedule PDF grid. API-Football id included only when already verified in UFO Predictor.",
  },
  {
    fixtureKey: "wc2026-match-063",
    matchNumber: 63,
    matchSlug: "world-cup-2026-egypt-vs-iran-2026-06-27",
    stage: "group_stage",
    groupKey: "group-g",
    roundLabel: "Group Stage",
    kickoffDateET: "2026-06-26",
    kickoffTimeET: "23:00",
    kickoffAt: "2026-06-27T03:00:00Z",
    timezone: "America/New_York",
    homeTeamKey: "egypt",
    awayTeamKey: "iran",
    homeTeamFifaCode: "EGY",
    awayTeamFifaCode: "IRN",
    venueKey: "seattle",
    hostCity: "Seattle",
    hostCountry: "USA",
    apiFootballFixtureId: null,
    apiFootballExternalId: null,
    statusHint: "scheduled",
    sourceNotes:
      "Extracted from FIFA official match schedule PDF grid. API-Football id included only when already verified in UFO Predictor.",
  },
  {
    fixtureKey: "wc2026-match-064",
    matchNumber: 64,
    matchSlug: "world-cup-2026-new-zealand-vs-belgium-2026-06-27",
    stage: "group_stage",
    groupKey: "group-g",
    roundLabel: "Group Stage",
    kickoffDateET: "2026-06-26",
    kickoffTimeET: "23:00",
    kickoffAt: "2026-06-27T03:00:00Z",
    timezone: "America/New_York",
    homeTeamKey: "new-zealand",
    awayTeamKey: "belgium",
    homeTeamFifaCode: "NZL",
    awayTeamFifaCode: "BEL",
    venueKey: "vancouver",
    hostCity: "Vancouver",
    hostCountry: "Canada",
    apiFootballFixtureId: null,
    apiFootballExternalId: null,
    statusHint: "scheduled",
    sourceNotes:
      "Extracted from FIFA official match schedule PDF grid. API-Football id included only when already verified in UFO Predictor.",
  },
  {
    fixtureKey: "wc2026-match-065",
    matchNumber: 65,
    matchSlug: "world-cup-2026-cabo-verde-vs-saudi-arabia-2026-06-27",
    stage: "group_stage",
    groupKey: "group-h",
    roundLabel: "Group Stage",
    kickoffDateET: "2026-06-26",
    kickoffTimeET: "20:00",
    kickoffAt: "2026-06-27T00:00:00Z",
    timezone: "America/New_York",
    homeTeamKey: "cabo-verde",
    awayTeamKey: "saudi-arabia",
    homeTeamFifaCode: "CPV",
    awayTeamFifaCode: "KSA",
    venueKey: "houston",
    hostCity: "Houston",
    hostCountry: "USA",
    apiFootballFixtureId: null,
    apiFootballExternalId: null,
    statusHint: "scheduled",
    sourceNotes:
      "Extracted from FIFA official match schedule PDF grid. API-Football id included only when already verified in UFO Predictor.",
  },
  {
    fixtureKey: "wc2026-match-066",
    matchNumber: 66,
    matchSlug: "world-cup-2026-uruguay-vs-spain-2026-06-27",
    stage: "group_stage",
    groupKey: "group-h",
    roundLabel: "Group Stage",
    kickoffDateET: "2026-06-26",
    kickoffTimeET: "20:00",
    kickoffAt: "2026-06-27T00:00:00Z",
    timezone: "America/New_York",
    homeTeamKey: "uruguay",
    awayTeamKey: "spain",
    homeTeamFifaCode: "URU",
    awayTeamFifaCode: "ESP",
    venueKey: "guadalajara",
    hostCity: "Guadalajara",
    hostCountry: "Mexico",
    apiFootballFixtureId: null,
    apiFootballExternalId: null,
    statusHint: "scheduled",
    sourceNotes:
      "Extracted from FIFA official match schedule PDF grid. API-Football id included only when already verified in UFO Predictor.",
  },
  {
    fixtureKey: "wc2026-match-067",
    matchNumber: 67,
    matchSlug: "world-cup-2026-panama-vs-england-2026-06-27",
    stage: "group_stage",
    groupKey: "group-l",
    roundLabel: "Group Stage",
    kickoffDateET: "2026-06-27",
    kickoffTimeET: "17:00",
    kickoffAt: "2026-06-27T21:00:00Z",
    timezone: "America/New_York",
    homeTeamKey: "panama",
    awayTeamKey: "england",
    homeTeamFifaCode: "PAN",
    awayTeamFifaCode: "ENG",
    venueKey: "new-york-new-jersey",
    hostCity: "New York New Jersey",
    hostCountry: "USA",
    apiFootballFixtureId: null,
    apiFootballExternalId: null,
    statusHint: "scheduled",
    sourceNotes:
      "Extracted from FIFA official match schedule PDF grid. API-Football id included only when already verified in UFO Predictor.",
  },
  {
    fixtureKey: "wc2026-match-068",
    matchNumber: 68,
    matchSlug: "world-cup-2026-croatia-vs-ghana-2026-06-27",
    stage: "group_stage",
    groupKey: "group-l",
    roundLabel: "Group Stage",
    kickoffDateET: "2026-06-27",
    kickoffTimeET: "17:00",
    kickoffAt: "2026-06-27T21:00:00Z",
    timezone: "America/New_York",
    homeTeamKey: "croatia",
    awayTeamKey: "ghana",
    homeTeamFifaCode: "CRO",
    awayTeamFifaCode: "GHA",
    venueKey: "philadelphia",
    hostCity: "Philadelphia",
    hostCountry: "USA",
    apiFootballFixtureId: null,
    apiFootballExternalId: null,
    statusHint: "scheduled",
    sourceNotes:
      "Extracted from FIFA official match schedule PDF grid. API-Football id included only when already verified in UFO Predictor.",
  },
  {
    fixtureKey: "wc2026-match-069",
    matchNumber: 69,
    matchSlug: "world-cup-2026-algeria-vs-austria-2026-06-28",
    stage: "group_stage",
    groupKey: "group-j",
    roundLabel: "Group Stage",
    kickoffDateET: "2026-06-27",
    kickoffTimeET: "22:00",
    kickoffAt: "2026-06-28T02:00:00Z",
    timezone: "America/New_York",
    homeTeamKey: "algeria",
    awayTeamKey: "austria",
    homeTeamFifaCode: "ALG",
    awayTeamFifaCode: "AUT",
    venueKey: "kansas-city",
    hostCity: "Kansas City",
    hostCountry: "USA",
    apiFootballFixtureId: null,
    apiFootballExternalId: null,
    statusHint: "scheduled",
    sourceNotes:
      "Extracted from FIFA official match schedule PDF grid. API-Football id included only when already verified in UFO Predictor.",
  },
  {
    fixtureKey: "wc2026-match-070",
    matchNumber: 70,
    matchSlug: "world-cup-2026-jordan-vs-argentina-2026-06-28",
    stage: "group_stage",
    groupKey: "group-j",
    roundLabel: "Group Stage",
    kickoffDateET: "2026-06-27",
    kickoffTimeET: "22:00",
    kickoffAt: "2026-06-28T02:00:00Z",
    timezone: "America/New_York",
    homeTeamKey: "jordan",
    awayTeamKey: "argentina",
    homeTeamFifaCode: "JOR",
    awayTeamFifaCode: "ARG",
    venueKey: "dallas",
    hostCity: "Dallas",
    hostCountry: "USA",
    apiFootballFixtureId: null,
    apiFootballExternalId: null,
    statusHint: "scheduled",
    sourceNotes:
      "Extracted from FIFA official match schedule PDF grid. API-Football id included only when already verified in UFO Predictor.",
  },
  {
    fixtureKey: "wc2026-match-071",
    matchNumber: 71,
    matchSlug: "world-cup-2026-colombia-vs-portugal-2026-06-27",
    stage: "group_stage",
    groupKey: "group-k",
    roundLabel: "Group Stage",
    kickoffDateET: "2026-06-27",
    kickoffTimeET: "19:30",
    kickoffAt: "2026-06-27T23:30:00Z",
    timezone: "America/New_York",
    homeTeamKey: "colombia",
    awayTeamKey: "portugal",
    homeTeamFifaCode: "COL",
    awayTeamFifaCode: "POR",
    venueKey: "miami",
    hostCity: "Miami",
    hostCountry: "USA",
    apiFootballFixtureId: null,
    apiFootballExternalId: null,
    statusHint: "scheduled",
    sourceNotes:
      "Extracted from FIFA official match schedule PDF grid. API-Football id included only when already verified in UFO Predictor.",
  },
  {
    fixtureKey: "wc2026-match-072",
    matchNumber: 72,
    matchSlug: "world-cup-2026-congo-dr-vs-uzbekistan-2026-06-27",
    stage: "group_stage",
    groupKey: "group-k",
    roundLabel: "Group Stage",
    kickoffDateET: "2026-06-27",
    kickoffTimeET: "19:30",
    kickoffAt: "2026-06-27T23:30:00Z",
    timezone: "America/New_York",
    homeTeamKey: "congo-dr",
    awayTeamKey: "uzbekistan",
    homeTeamFifaCode: "COD",
    awayTeamFifaCode: "UZB",
    venueKey: "atlanta",
    hostCity: "Atlanta",
    hostCountry: "USA",
    apiFootballFixtureId: null,
    apiFootballExternalId: null,
    statusHint: "scheduled",
    sourceNotes:
      "Extracted from FIFA official match schedule PDF grid. API-Football id included only when already verified in UFO Predictor.",
  },
  {
    fixtureKey: "wc2026-match-073",
    matchNumber: 73,
    matchSlug: "world-cup-2026-south-africa-vs-canada-2026-06-28",
    stage: "round_of_32",
    groupKey: "",
    roundLabel: "Round of 32",
    kickoffDateET: "2026-06-28",
    kickoffTimeET: "15:00",
    kickoffAt: "2026-06-28T19:00:00Z",
    timezone: "America/New_York",
    homeTeamKey: "south-africa",
    awayTeamKey: "canada",
    homeTeamFifaCode: "RSA",
    awayTeamFifaCode: "CAN",
    venueKey: "los-angeles",
    hostCity: "Los Angeles",
    hostCountry: "USA",
    apiFootballFixtureId: 1561329,
    apiFootballExternalId: "api-football:fixture:1561329",
    statusHint: "scheduled",
    sourceNotes:
      "Official FIFA Round of 32 schedule row 73 (2A vs 2B) resolved with verified 2026-06-30 API-Football participant identity.",
  },
  {
    fixtureKey: "wc2026-match-074",
    matchNumber: 74,
    matchSlug: "world-cup-2026-germany-vs-paraguay-2026-06-29",
    stage: "round_of_32",
    groupKey: "",
    roundLabel: "Round of 32",
    kickoffDateET: "2026-06-29",
    kickoffTimeET: "16:30",
    kickoffAt: "2026-06-29T20:30:00Z",
    timezone: "America/New_York",
    homeTeamKey: "germany",
    awayTeamKey: "paraguay",
    homeTeamFifaCode: "GER",
    awayTeamFifaCode: "PAR",
    venueKey: "boston",
    hostCity: "Boston",
    hostCountry: "USA",
    apiFootballFixtureId: 1565176,
    apiFootballExternalId: "api-football:fixture:1565176",
    statusHint: "scheduled",
    sourceNotes:
      "Official FIFA Round of 32 schedule row 74 (1E vs 3ABCDF) resolved with verified 2026-06-30 API-Football participant identity.",
  },
  {
    fixtureKey: "wc2026-match-075",
    matchNumber: 75,
    matchSlug: "world-cup-2026-netherlands-vs-morocco-2026-06-29",
    stage: "round_of_32",
    groupKey: "",
    roundLabel: "Round of 32",
    kickoffDateET: "2026-06-29",
    kickoffTimeET: "21:00",
    kickoffAt: "2026-06-30T01:00:00Z",
    timezone: "America/New_York",
    homeTeamKey: "netherlands",
    awayTeamKey: "morocco",
    homeTeamFifaCode: "NED",
    awayTeamFifaCode: "MAR",
    venueKey: "monterrey",
    hostCity: "Monterrey",
    hostCountry: "Mexico",
    apiFootballFixtureId: 1562345,
    apiFootballExternalId: "api-football:fixture:1562345",
    statusHint: "scheduled",
    sourceNotes:
      "Official FIFA Round of 32 schedule row 75 (1F vs 2C) resolved with verified 2026-06-30 API-Football participant identity.",
  },
  {
    fixtureKey: "wc2026-match-076",
    matchNumber: 76,
    matchSlug: "world-cup-2026-brazil-vs-japan-2026-06-29",
    stage: "round_of_32",
    groupKey: "",
    roundLabel: "Round of 32",
    kickoffDateET: "2026-06-29",
    kickoffTimeET: "13:00",
    kickoffAt: "2026-06-29T17:00:00Z",
    timezone: "America/New_York",
    homeTeamKey: "brazil",
    awayTeamKey: "japan",
    homeTeamFifaCode: "BRA",
    awayTeamFifaCode: "JPN",
    venueKey: "houston",
    hostCity: "Houston",
    hostCountry: "USA",
    apiFootballFixtureId: 1562344,
    apiFootballExternalId: "api-football:fixture:1562344",
    statusHint: "scheduled",
    sourceNotes:
      "Official FIFA Round of 32 schedule row 76 (1C vs 2F) resolved with verified 2026-06-30 API-Football participant identity.",
  },
  {
    fixtureKey: "wc2026-match-077",
    matchNumber: 77,
    matchSlug: "world-cup-2026-france-vs-sweden-2026-06-30",
    stage: "round_of_32",
    groupKey: "",
    roundLabel: "Round of 32",
    kickoffDateET: "2026-06-30",
    kickoffTimeET: "17:00",
    kickoffAt: "2026-06-30T21:00:00Z",
    timezone: "America/New_York",
    homeTeamKey: "france",
    awayTeamKey: "sweden",
    homeTeamFifaCode: "FRA",
    awayTeamFifaCode: "SWE",
    venueKey: "new-york-new-jersey",
    hostCity: "New York New Jersey",
    hostCountry: "USA",
    apiFootballFixtureId: 1565177,
    apiFootballExternalId: "api-football:fixture:1565177",
    statusHint: "scheduled",
    sourceNotes:
      "Official FIFA Round of 32 schedule row 77 (1I vs 3CDFGH) resolved with verified 2026-06-30 API-Football participant identity.",
  },
  {
    fixtureKey: "wc2026-match-078",
    matchNumber: 78,
    matchSlug: "world-cup-2026-cote-divoire-vs-norway-2026-06-30",
    stage: "round_of_32",
    groupKey: "",
    roundLabel: "Round of 32",
    kickoffDateET: "2026-06-30",
    kickoffTimeET: "13:00",
    kickoffAt: "2026-06-30T17:00:00Z",
    timezone: "America/New_York",
    homeTeamKey: "cote-divoire",
    awayTeamKey: "norway",
    homeTeamFifaCode: "CIV",
    awayTeamFifaCode: "NOR",
    venueKey: "dallas",
    hostCity: "Dallas",
    hostCountry: "USA",
    apiFootballFixtureId: 1564789,
    apiFootballExternalId: "api-football:fixture:1564789",
    statusHint: "scheduled",
    sourceNotes:
      "Official FIFA Round of 32 schedule row 78 (2E vs 2I) resolved with verified 2026-06-30 API-Football participant identity.",
  },
  {
    fixtureKey: "wc2026-match-079",
    matchNumber: 79,
    matchSlug: "world-cup-2026-mexico-vs-ecuador-2026-06-30",
    stage: "round_of_32",
    groupKey: "",
    roundLabel: "Round of 32",
    kickoffDateET: "2026-06-30",
    kickoffTimeET: "21:00",
    kickoffAt: "2026-07-01T01:00:00Z",
    timezone: "America/New_York",
    homeTeamKey: "mexico",
    awayTeamKey: "ecuador",
    homeTeamFifaCode: "MEX",
    awayTeamFifaCode: "ECU",
    venueKey: "mexico-city",
    hostCity: "Mexico City",
    hostCountry: "Mexico",
    apiFootballFixtureId: 1567306,
    apiFootballExternalId: "api-football:fixture:1567306",
    statusHint: "scheduled",
    sourceNotes:
      "Official FIFA Round of 32 schedule row 79 (1A vs 3CEFHI) resolved with verified 2026-06-30 API-Football participant identity.",
  },
  {
    fixtureKey: "wc2026-match-080",
    matchNumber: 80,
    matchSlug: "world-cup-2026-england-vs-congo-dr-2026-07-01",
    stage: "round_of_32",
    groupKey: "",
    roundLabel: "Round of 32",
    kickoffDateET: "2026-07-01",
    kickoffTimeET: "12:00",
    kickoffAt: "2026-07-01T16:00:00Z",
    timezone: "America/New_York",
    homeTeamKey: "england",
    awayTeamKey: "congo-dr",
    homeTeamFifaCode: "ENG",
    awayTeamFifaCode: "COD",
    venueKey: "atlanta",
    hostCity: "Atlanta",
    hostCountry: "USA",
    apiFootballFixtureId: 1567307,
    apiFootballExternalId: "api-football:fixture:1567307",
    statusHint: "scheduled",
    sourceNotes:
      "Official FIFA Round of 32 schedule row 80 (1L vs 3EHIJK) resolved with verified 2026-06-30 API-Football participant identity.",
  },
  {
    fixtureKey: "wc2026-match-081",
    matchNumber: 81,
    matchSlug: "world-cup-2026-usa-vs-bosnia-herzegovina-2026-07-01",
    stage: "round_of_32",
    groupKey: "",
    roundLabel: "Round of 32",
    kickoffDateET: "2026-07-01",
    kickoffTimeET: "20:00",
    kickoffAt: "2026-07-02T00:00:00Z",
    timezone: "America/New_York",
    homeTeamKey: "usa",
    awayTeamKey: "bosnia-herzegovina",
    homeTeamFifaCode: "USA",
    awayTeamFifaCode: "BIH",
    venueKey: "san-francisco-bay-area",
    hostCity: "San Francisco Bay Area",
    hostCountry: "USA",
    apiFootballFixtureId: 1562586,
    apiFootballExternalId: "api-football:fixture:1562586",
    statusHint: "scheduled",
    sourceNotes:
      "Official FIFA Round of 32 schedule row 81 (1D vs 3BEFIJ) resolved with verified 2026-06-30 API-Football participant identity.",
  },
  {
    fixtureKey: "wc2026-match-082",
    matchNumber: 82,
    matchSlug: "world-cup-2026-belgium-vs-senegal-2026-07-01",
    stage: "round_of_32",
    groupKey: "",
    roundLabel: "Round of 32",
    kickoffDateET: "2026-07-01",
    kickoffTimeET: "16:00",
    kickoffAt: "2026-07-01T20:00:00Z",
    timezone: "America/New_York",
    homeTeamKey: "belgium",
    awayTeamKey: "senegal",
    homeTeamFifaCode: "BEL",
    awayTeamFifaCode: "SEN",
    venueKey: "seattle",
    hostCity: "Seattle",
    hostCountry: "USA",
    apiFootballFixtureId: 1567308,
    apiFootballExternalId: "api-football:fixture:1567308",
    statusHint: "scheduled",
    sourceNotes:
      "Official FIFA Round of 32 schedule row 82 (1G vs 3AEHIJ) resolved with verified 2026-06-30 API-Football participant identity.",
  },
  {
    fixtureKey: "wc2026-match-083",
    matchNumber: 83,
    matchSlug: "world-cup-2026-portugal-vs-croatia-2026-07-02",
    stage: "round_of_32",
    groupKey: "",
    roundLabel: "Round of 32",
    kickoffDateET: "2026-07-02",
    kickoffTimeET: "19:00",
    kickoffAt: "2026-07-02T23:00:00Z",
    timezone: "America/New_York",
    homeTeamKey: "portugal",
    awayTeamKey: "croatia",
    homeTeamFifaCode: "POR",
    awayTeamFifaCode: "CRO",
    venueKey: "toronto",
    hostCity: "Toronto",
    hostCountry: "Canada",
    apiFootballFixtureId: 1567309,
    apiFootballExternalId: "api-football:fixture:1567309",
    statusHint: "scheduled",
    sourceNotes:
      "Official FIFA Round of 32 schedule row 83 (2K vs 2L) resolved with verified 2026-06-30 API-Football participant identity.",
  },
  {
    fixtureKey: "wc2026-match-084",
    matchNumber: 84,
    matchSlug: "world-cup-2026-spain-vs-austria-2026-07-02",
    stage: "round_of_32",
    groupKey: "",
    roundLabel: "Round of 32",
    kickoffDateET: "2026-07-02",
    kickoffTimeET: "15:00",
    kickoffAt: "2026-07-02T19:00:00Z",
    timezone: "America/New_York",
    homeTeamKey: "spain",
    awayTeamKey: "austria",
    homeTeamFifaCode: "ESP",
    awayTeamFifaCode: "AUT",
    venueKey: "los-angeles",
    hostCity: "Los Angeles",
    hostCountry: "USA",
    apiFootballFixtureId: 1567311,
    apiFootballExternalId: "api-football:fixture:1567311",
    statusHint: "scheduled",
    sourceNotes:
      "Official FIFA Round of 32 schedule row 84 (1H vs 2J) resolved with verified 2026-06-30 API-Football participant identity.",
  },
  {
    fixtureKey: "wc2026-match-085",
    matchNumber: 85,
    matchSlug: "world-cup-2026-switzerland-vs-algeria-2026-07-02",
    stage: "round_of_32",
    groupKey: "",
    roundLabel: "Round of 32",
    kickoffDateET: "2026-07-02",
    kickoffTimeET: "23:00",
    kickoffAt: "2026-07-03T03:00:00Z",
    timezone: "America/New_York",
    homeTeamKey: "switzerland",
    awayTeamKey: "algeria",
    homeTeamFifaCode: "SUI",
    awayTeamFifaCode: "ALG",
    venueKey: "vancouver",
    hostCity: "Vancouver",
    hostCountry: "Canada",
    apiFootballFixtureId: 1567312,
    apiFootballExternalId: "api-football:fixture:1567312",
    statusHint: "scheduled",
    sourceNotes:
      "Official FIFA Round of 32 schedule row 85 (1B vs 3EFGIJ) resolved with verified 2026-06-30 API-Football participant identity.",
  },
  {
    fixtureKey: "wc2026-match-086",
    matchNumber: 86,
    matchSlug: "world-cup-2026-argentina-vs-cabo-verde-2026-07-03",
    stage: "round_of_32",
    groupKey: "",
    roundLabel: "Round of 32",
    kickoffDateET: "2026-07-03",
    kickoffTimeET: "18:00",
    kickoffAt: "2026-07-03T22:00:00Z",
    timezone: "America/New_York",
    homeTeamKey: "argentina",
    awayTeamKey: "cabo-verde",
    homeTeamFifaCode: "ARG",
    awayTeamFifaCode: "CPV",
    venueKey: "miami",
    hostCity: "Miami",
    hostCountry: "USA",
    apiFootballFixtureId: 1565179,
    apiFootballExternalId: "api-football:fixture:1565179",
    statusHint: "scheduled",
    sourceNotes:
      "Official FIFA Round of 32 schedule row 86 (1J vs 2H) resolved with verified 2026-06-30 API-Football participant identity.",
  },
  {
    fixtureKey: "wc2026-match-087",
    matchNumber: 87,
    matchSlug: "world-cup-2026-colombia-vs-ghana-2026-07-03",
    stage: "round_of_32",
    groupKey: "",
    roundLabel: "Round of 32",
    kickoffDateET: "2026-07-03",
    kickoffTimeET: "21:30",
    kickoffAt: "2026-07-04T01:30:00Z",
    timezone: "America/New_York",
    homeTeamKey: "colombia",
    awayTeamKey: "ghana",
    homeTeamFifaCode: "COL",
    awayTeamFifaCode: "GHA",
    venueKey: "kansas-city",
    hostCity: "Kansas City",
    hostCountry: "USA",
    apiFootballFixtureId: 1567310,
    apiFootballExternalId: "api-football:fixture:1567310",
    statusHint: "scheduled",
    sourceNotes:
      "Official FIFA Round of 32 schedule row 87 (1K vs 3DEIJL) resolved with verified 2026-06-30 API-Football participant identity.",
  },
  {
    fixtureKey: "wc2026-match-088",
    matchNumber: 88,
    matchSlug: "world-cup-2026-australia-vs-egypt-2026-07-03",
    stage: "round_of_32",
    groupKey: "",
    roundLabel: "Round of 32",
    kickoffDateET: "2026-07-03",
    kickoffTimeET: "14:00",
    kickoffAt: "2026-07-03T18:00:00Z",
    timezone: "America/New_York",
    homeTeamKey: "australia",
    awayTeamKey: "egypt",
    homeTeamFifaCode: "AUS",
    awayTeamFifaCode: "EGY",
    venueKey: "dallas",
    hostCity: "Dallas",
    hostCountry: "USA",
    apiFootballFixtureId: 1565178,
    apiFootballExternalId: "api-football:fixture:1565178",
    statusHint: "scheduled",
    sourceNotes:
      "Official FIFA Round of 32 schedule row 88 (2D vs 2G) resolved with verified 2026-06-30 API-Football participant identity.",
  },
] as const satisfies readonly WorldCup2026Fixture[];
