import type { WorldCup2026Team } from "./types";

export const WORLD_CUP_2026_TEAMS = [
  {
    teamKey: "mexico",
    displayName: "Mexico",
    fifaOfficialName: "Mexico",
    slug: "mexico",
    fifaCode: "MEX",
    country: "Mexico",
    groupKey: "group-a",
    aliases: ["MEX", "Mexico", "México"],
    apiFootballTeamId: null,
    notes: null,
  },
  {
    teamKey: "south-africa",
    displayName: "South Africa",
    fifaOfficialName: "South Africa",
    slug: "south-africa",
    fifaCode: "RSA",
    country: "South Africa",
    groupKey: "group-a",
    aliases: ["RSA", "South Africa"],
    apiFootballTeamId: null,
    notes: null,
  },
  {
    teamKey: "south-korea",
    displayName: "South Korea",
    fifaOfficialName: "Korea Republic",
    slug: "south-korea",
    fifaCode: "KOR",
    country: "South Korea",
    groupKey: "group-a",
    aliases: ["KOR", "Korea Republic", "Republic of Korea", "South Korea"],
    apiFootballTeamId: null,
    notes: null,
  },
  {
    teamKey: "czech-republic",
    displayName: "Czech Republic",
    fifaOfficialName: "Czechia",
    slug: "czech-republic",
    fifaCode: "CZE",
    country: "Czech Republic",
    groupKey: "group-a",
    aliases: ["CZE", "Czech Republic", "Czechia"],
    apiFootballTeamId: null,
    notes: null,
  },
  {
    teamKey: "canada",
    displayName: "Canada",
    fifaOfficialName: "Canada",
    slug: "canada",
    fifaCode: "CAN",
    country: "Canada",
    groupKey: "group-b",
    aliases: ["CAN", "Canada"],
    apiFootballTeamId: null,
    notes: null,
  },
  {
    teamKey: "bosnia-herzegovina",
    displayName: "Bosnia & Herzegovina",
    fifaOfficialName: "Bosnia & Herzegovina",
    slug: "bosnia-herzegovina",
    fifaCode: "BIH",
    country: "Bosnia & Herzegovina",
    groupKey: "group-b",
    aliases: ["BIH", "Bosnia & Herzegovina", "Bosnia and Herzegovina"],
    apiFootballTeamId: null,
    notes: null,
  },
  {
    teamKey: "qatar",
    displayName: "Qatar",
    fifaOfficialName: "Qatar",
    slug: "qatar",
    fifaCode: "QAT",
    country: "Qatar",
    groupKey: "group-b",
    aliases: ["QAT", "Qatar"],
    apiFootballTeamId: null,
    notes: null,
  },
  {
    teamKey: "switzerland",
    displayName: "Switzerland",
    fifaOfficialName: "Switzerland",
    slug: "switzerland",
    fifaCode: "SUI",
    country: "Switzerland",
    groupKey: "group-b",
    aliases: ["SUI", "Switzerland"],
    apiFootballTeamId: null,
    notes: null,
  },
  {
    teamKey: "brazil",
    displayName: "Brazil",
    fifaOfficialName: "Brazil",
    slug: "brazil",
    fifaCode: "BRA",
    country: "Brazil",
    groupKey: "group-c",
    aliases: ["BRA", "Brazil"],
    apiFootballTeamId: null,
    notes: null,
  },
  {
    teamKey: "morocco",
    displayName: "Morocco",
    fifaOfficialName: "Morocco",
    slug: "morocco",
    fifaCode: "MAR",
    country: "Morocco",
    groupKey: "group-c",
    aliases: ["MAR", "Morocco"],
    apiFootballTeamId: null,
    notes: null,
  },
  {
    teamKey: "haiti",
    displayName: "Haiti",
    fifaOfficialName: "Haiti",
    slug: "haiti",
    fifaCode: "HAI",
    country: "Haiti",
    groupKey: "group-c",
    aliases: ["HAI", "Haiti"],
    apiFootballTeamId: null,
    notes: null,
  },
  {
    teamKey: "scotland",
    displayName: "Scotland",
    fifaOfficialName: "Scotland",
    slug: "scotland",
    fifaCode: "SCO",
    country: "Scotland",
    groupKey: "group-c",
    aliases: ["SCO", "Scotland"],
    apiFootballTeamId: null,
    notes: null,
  },
  {
    teamKey: "usa",
    displayName: "USA",
    fifaOfficialName: "USA",
    slug: "usa",
    fifaCode: "USA",
    country: "USA",
    groupKey: "group-d",
    aliases: ["USA", "United States", "United States of America"],
    apiFootballTeamId: null,
    notes: null,
  },
  {
    teamKey: "paraguay",
    displayName: "Paraguay",
    fifaOfficialName: "Paraguay",
    slug: "paraguay",
    fifaCode: "PAR",
    country: "Paraguay",
    groupKey: "group-d",
    aliases: ["PAR", "Paraguay"],
    apiFootballTeamId: null,
    notes: null,
  },
  {
    teamKey: "australia",
    displayName: "Australia",
    fifaOfficialName: "Australia",
    slug: "australia",
    fifaCode: "AUS",
    country: "Australia",
    groupKey: "group-d",
    aliases: ["AUS", "Australia"],
    apiFootballTeamId: null,
    notes: null,
  },
  {
    teamKey: "turkiye",
    displayName: "Türkiye",
    fifaOfficialName: "Türkiye",
    slug: "turkiye",
    fifaCode: "TUR",
    country: "Türkiye",
    groupKey: "group-d",
    aliases: ["TUR", "Turkey", "Turkiye", "Türkiye"],
    apiFootballTeamId: null,
    notes: null,
  },
  {
    teamKey: "germany",
    displayName: "Germany",
    fifaOfficialName: "Germany",
    slug: "germany",
    fifaCode: "GER",
    country: "Germany",
    groupKey: "group-e",
    aliases: ["GER", "Germany"],
    apiFootballTeamId: null,
    notes: null,
  },
  {
    teamKey: "curacao",
    displayName: "Curaçao",
    fifaOfficialName: "Curaçao",
    slug: "curacao",
    fifaCode: "CUW",
    country: "Curaçao",
    groupKey: "group-e",
    aliases: ["CUW", "Curacao", "Curaçao"],
    apiFootballTeamId: null,
    notes: null,
  },
  {
    teamKey: "cote-divoire",
    displayName: "Côte d’Ivoire",
    fifaOfficialName: "Côte d’Ivoire",
    slug: "cote-divoire",
    fifaCode: "CIV",
    country: "Côte d’Ivoire",
    groupKey: "group-e",
    aliases: ["CIV", "Cote d Ivoire", "Cote d’Ivoire", "Côte d’Ivoire", "Ivory Coast"],
    apiFootballTeamId: null,
    notes: null,
  },
  {
    teamKey: "ecuador",
    displayName: "Ecuador",
    fifaOfficialName: "Ecuador",
    slug: "ecuador",
    fifaCode: "ECU",
    country: "Ecuador",
    groupKey: "group-e",
    aliases: ["ECU", "Ecuador"],
    apiFootballTeamId: null,
    notes: null,
  },
  {
    teamKey: "netherlands",
    displayName: "Netherlands",
    fifaOfficialName: "Netherlands",
    slug: "netherlands",
    fifaCode: "NED",
    country: "Netherlands",
    groupKey: "group-f",
    aliases: ["Holland", "NED", "Netherlands"],
    apiFootballTeamId: null,
    notes: null,
  },
  {
    teamKey: "japan",
    displayName: "Japan",
    fifaOfficialName: "Japan",
    slug: "japan",
    fifaCode: "JPN",
    country: "Japan",
    groupKey: "group-f",
    aliases: ["JPN", "Japan"],
    apiFootballTeamId: null,
    notes: null,
  },
  {
    teamKey: "sweden",
    displayName: "Sweden",
    fifaOfficialName: "Sweden",
    slug: "sweden",
    fifaCode: "SWE",
    country: "Sweden",
    groupKey: "group-f",
    aliases: ["SWE", "Sweden"],
    apiFootballTeamId: null,
    notes: null,
  },
  {
    teamKey: "tunisia",
    displayName: "Tunisia",
    fifaOfficialName: "Tunisia",
    slug: "tunisia",
    fifaCode: "TUN",
    country: "Tunisia",
    groupKey: "group-f",
    aliases: ["TUN", "Tunisia"],
    apiFootballTeamId: null,
    notes: null,
  },
  {
    teamKey: "belgium",
    displayName: "Belgium",
    fifaOfficialName: "Belgium",
    slug: "belgium",
    fifaCode: "BEL",
    country: "Belgium",
    groupKey: "group-g",
    aliases: ["BEL", "Belgium"],
    apiFootballTeamId: null,
    notes: null,
  },
  {
    teamKey: "egypt",
    displayName: "Egypt",
    fifaOfficialName: "Egypt",
    slug: "egypt",
    fifaCode: "EGY",
    country: "Egypt",
    groupKey: "group-g",
    aliases: ["EGY", "Egypt"],
    apiFootballTeamId: null,
    notes: null,
  },
  {
    teamKey: "iran",
    displayName: "IR Iran",
    fifaOfficialName: "IR Iran",
    slug: "iran",
    fifaCode: "IRN",
    country: "IR Iran",
    groupKey: "group-g",
    aliases: ["IR Iran", "IRN", "Iran"],
    apiFootballTeamId: null,
    notes: null,
  },
  {
    teamKey: "new-zealand",
    displayName: "New Zealand",
    fifaOfficialName: "New Zealand",
    slug: "new-zealand",
    fifaCode: "NZL",
    country: "New Zealand",
    groupKey: "group-g",
    aliases: ["NZL", "New Zealand"],
    apiFootballTeamId: null,
    notes: null,
  },
  {
    teamKey: "spain",
    displayName: "Spain",
    fifaOfficialName: "Spain",
    slug: "spain",
    fifaCode: "ESP",
    country: "Spain",
    groupKey: "group-h",
    aliases: ["ESP", "Spain"],
    apiFootballTeamId: null,
    notes: null,
  },
  {
    teamKey: "cabo-verde",
    displayName: "Cabo Verde",
    fifaOfficialName: "Cabo Verde",
    slug: "cabo-verde",
    fifaCode: "CPV",
    country: "Cabo Verde",
    groupKey: "group-h",
    aliases: ["CPV", "Cabo Verde", "Cape Verde"],
    apiFootballTeamId: null,
    notes: null,
  },
  {
    teamKey: "saudi-arabia",
    displayName: "Saudi Arabia",
    fifaOfficialName: "Saudi Arabia",
    slug: "saudi-arabia",
    fifaCode: "KSA",
    country: "Saudi Arabia",
    groupKey: "group-h",
    aliases: ["KSA", "Saudi Arabia"],
    apiFootballTeamId: null,
    notes: null,
  },
  {
    teamKey: "uruguay",
    displayName: "Uruguay",
    fifaOfficialName: "Uruguay",
    slug: "uruguay",
    fifaCode: "URU",
    country: "Uruguay",
    groupKey: "group-h",
    aliases: ["URU", "Uruguay"],
    apiFootballTeamId: null,
    notes: null,
  },
  {
    teamKey: "france",
    displayName: "France",
    fifaOfficialName: "France",
    slug: "france",
    fifaCode: "FRA",
    country: "France",
    groupKey: "group-i",
    aliases: ["FRA", "France"],
    apiFootballTeamId: null,
    notes: null,
  },
  {
    teamKey: "senegal",
    displayName: "Senegal",
    fifaOfficialName: "Senegal",
    slug: "senegal",
    fifaCode: "SEN",
    country: "Senegal",
    groupKey: "group-i",
    aliases: ["SEN", "Senegal"],
    apiFootballTeamId: null,
    notes: null,
  },
  {
    teamKey: "iraq",
    displayName: "Iraq",
    fifaOfficialName: "Iraq",
    slug: "iraq",
    fifaCode: "IRQ",
    country: "Iraq",
    groupKey: "group-i",
    aliases: ["IRQ", "Iraq"],
    apiFootballTeamId: null,
    notes: null,
  },
  {
    teamKey: "norway",
    displayName: "Norway",
    fifaOfficialName: "Norway",
    slug: "norway",
    fifaCode: "NOR",
    country: "Norway",
    groupKey: "group-i",
    aliases: ["NOR", "Norway"],
    apiFootballTeamId: null,
    notes: null,
  },
  {
    teamKey: "argentina",
    displayName: "Argentina",
    fifaOfficialName: "Argentina",
    slug: "argentina",
    fifaCode: "ARG",
    country: "Argentina",
    groupKey: "group-j",
    aliases: ["ARG", "Argentina"],
    apiFootballTeamId: null,
    notes: null,
  },
  {
    teamKey: "algeria",
    displayName: "Algeria",
    fifaOfficialName: "Algeria",
    slug: "algeria",
    fifaCode: "ALG",
    country: "Algeria",
    groupKey: "group-j",
    aliases: ["ALG", "Algeria"],
    apiFootballTeamId: null,
    notes: null,
  },
  {
    teamKey: "austria",
    displayName: "Austria",
    fifaOfficialName: "Austria",
    slug: "austria",
    fifaCode: "AUT",
    country: "Austria",
    groupKey: "group-j",
    aliases: ["AUT", "Austria"],
    apiFootballTeamId: null,
    notes: null,
  },
  {
    teamKey: "jordan",
    displayName: "Jordan",
    fifaOfficialName: "Jordan",
    slug: "jordan",
    fifaCode: "JOR",
    country: "Jordan",
    groupKey: "group-j",
    aliases: ["JOR", "Jordan"],
    apiFootballTeamId: null,
    notes: null,
  },
  {
    teamKey: "portugal",
    displayName: "Portugal",
    fifaOfficialName: "Portugal",
    slug: "portugal",
    fifaCode: "POR",
    country: "Portugal",
    groupKey: "group-k",
    aliases: ["POR", "Portugal"],
    apiFootballTeamId: null,
    notes: null,
  },
  {
    teamKey: "congo-dr",
    displayName: "Congo DR",
    fifaOfficialName: "Congo DR",
    slug: "congo-dr",
    fifaCode: "COD",
    country: "Congo DR",
    groupKey: "group-k",
    aliases: ["COD", "Congo DR", "DR Congo", "Democratic Republic of the Congo"],
    apiFootballTeamId: null,
    notes: null,
  },
  {
    teamKey: "uzbekistan",
    displayName: "Uzbekistan",
    fifaOfficialName: "Uzbekistan",
    slug: "uzbekistan",
    fifaCode: "UZB",
    country: "Uzbekistan",
    groupKey: "group-k",
    aliases: ["UZB", "Uzbekistan"],
    apiFootballTeamId: null,
    notes: null,
  },
  {
    teamKey: "colombia",
    displayName: "Colombia",
    fifaOfficialName: "Colombia",
    slug: "colombia",
    fifaCode: "COL",
    country: "Colombia",
    groupKey: "group-k",
    aliases: ["COL", "Colombia"],
    apiFootballTeamId: null,
    notes: null,
  },
  {
    teamKey: "england",
    displayName: "England",
    fifaOfficialName: "England",
    slug: "england",
    fifaCode: "ENG",
    country: "England",
    groupKey: "group-l",
    aliases: ["ENG", "England"],
    apiFootballTeamId: null,
    notes: null,
  },
  {
    teamKey: "croatia",
    displayName: "Croatia",
    fifaOfficialName: "Croatia",
    slug: "croatia",
    fifaCode: "CRO",
    country: "Croatia",
    groupKey: "group-l",
    aliases: ["CRO", "Croatia"],
    apiFootballTeamId: null,
    notes: null,
  },
  {
    teamKey: "ghana",
    displayName: "Ghana",
    fifaOfficialName: "Ghana",
    slug: "ghana",
    fifaCode: "GHA",
    country: "Ghana",
    groupKey: "group-l",
    aliases: ["GHA", "Ghana"],
    apiFootballTeamId: null,
    notes: null,
  },
  {
    teamKey: "panama",
    displayName: "Panama",
    fifaOfficialName: "Panama",
    slug: "panama",
    fifaCode: "PAN",
    country: "Panama",
    groupKey: "group-l",
    aliases: ["PAN", "Panama", "Panamá"],
    apiFootballTeamId: null,
    notes: null,
  },
] as const satisfies readonly WorldCup2026Team[];
